#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  7 09:48:28 2017

@author: rhdzmota
"""

# %% Imports 

import numpy as np


# %% name2desc

name2desc = {
    
    'AC':'ARCA CONTINENTAL ES UNA EMPRESA CONTROLADORA, CUYAS PRINCIPALES SUBSIDIARIAS SE DEDICAN A LA PRODUCCION Y COMERCIALIZACION DE BEBIDAS CARBONATADAS, NO CARBONATADAS Y BOTANAS.',
    'ACCELSA':'TENEDORA DE EMPRESAS DEDICADAS A ACTIVIDADES INMOBILIARIAS, SERVICIOS DE MANUFACTURA, PRESTACION DE SERVICIOS DE ALMACENAJE, LOGISTICA Y DISTRIBUCION, ASI COMO DISEÑO, FABRICACION Y VENTA ROPA.',
    'AEROMEX':'SOCIEDAD CONTROLADORA A TRAVES DE SUS SUBSIDIARIAS REALIZA ACTIVIDADES DE TRANSPORTE AEREO',
    'AGRIEXP':'COMPRA, PROCESAMIENTO Y COMERCIALIZACION DE FRUTAS Y VERDURAS PROCESADAS.',
    'AGUA':'PRODUCTOS RELACIONADOS CON EL AGUA. PROVEE SOLUCIONES INDIVIDUALES E INTEGRALES PARA EL ALMACENAMIENTO, CONDUCCIÓN Y MEJORAMIENTO DEL AGUA.',
    'AHMSA':'EMPRESA FABRICANTE DE ACERO Y MANUFACTURERA DE PRODUCTOS RELAMINABLES, PLANOS, NO PLANOS Y TUBERIA CON COSTURA, ASI COMO SUBPRODUCTOS DERIVADOS DEL GAS DE COQUE.',
    'ALFA':'CONTROLADORA DE EMPRESAS INDUSTRIALES EN AREAS DIVERSIFICADAS.',
    'ALPEK':'CONTROLADORA DE EMPRESAS DEDICADAS A LAS INDUSTRIAS PETROQUIMICAS, PLASTICAS Y FIBRAS SINTETICAS.',
    'ALSEA':'OPERADOR LÍDER DE ESTABLECIMIENTOS DE COMIDA RÁPIDA, CAFETERÍAS Y COMIDA CASUAL EN AMÉRICA LATINA Y ESPAÑA.',
    'AMX':'PROPORCIONAR SERVICIOS DE TELECOMUNICACIONES A NIVEL NACIONAL O INTERNACIONAL A CLIENTES RESIDENCIALES Y COMERCIALES QUE OPERAN EN UNA AMPLIA GAMA DE ACTIVIDADES.',
    'ARA':'CONSTRUCCION DE VIVIENDA DE INTERES SOCIAL, TIPO MEDIA, RESIDENCIAL Y TURISTICA.',
    'ARISTOS':'CONSTRUCCIÓN DE OBRA PÚBLICA Y PRIVADA Y DE ESTRUCTURAS DE ACERO Y TORRES DE TRANSMISIÓN ELÉCTRICA, ASÍ COMO MANEJO DE RELLENOS SANITARIOS.',
    'ASUR':'ADMINISTRACION, OPERACION INCLUYENDO LA PRESTACION DE SERVICIOS AEROPORTUARIOS, COMPLEMENTARIOS Y COMERCIALES, CONSTRUCCION Y/O EXPLOTACION DE AERODROMOS CIVILES.',
    'AUTLAN':'PRODUCCIÓN Y COMERCIALIZACIÓN DE MINERALES DE MANGANESO Y FERROALEACIONES.',
    'AXTEL':'SERVICIOS DE TELECOMUNICACIONES.',
    'AZTECA':'PRODUCCION DE PROGRAMACION PARA SER TRANSMITIDAS A TRAVES DE SUS PROPIAS REDES, ASI COMO A LA VENTA DE LA MISMA A NIVEL NACIONAL Y VENTA DE TIEMPO DE PUBLICIDAD.',
    'BACHOCO':'TENEDORA PURA DE ACCIONES, A TRAVES DE SUS SUBSIDIARIAS PRODUCCION PROCESAMIENTO Y COMERCIALIZACION DE POLLO, PRODUCCION Y COMERCIALIZACION DE HUEVO, PRODUCCION Y VENTA DE CERDO.',
    'BAFAR':'CONTROLADORA DE EMPRESAS DEDICADAS A LA ELABORACION, DISTRIBUCION Y COMERCIALIZACION DE ALIMENTOS PROCESADOS; COMPRA-VENTA DE CARNES, ENGORDA Y COMERCIALIZACION DE GANADO BOVINO EN PIE.',
    'BEVIDES':'CONTROLADORA DE EMPRESAS COMERCIALES DEDICADAS A LA COMERCIALIZACION DIRECTA CON EL ULTIMO CONSUMIDOR DE PRODUCTOS RELACIONADOS CON EL BIENESTAR Y LA SALUD.',
    'BIMBO':'PAN EMPACADO, PASTELERIA DE TIPO CASERO, GALLETAS, DULCES, CHOCOLATES, BOTANAS DULCES Y SALADAS, TORTILLAS EMPACADAS DE MAIZ Y DE HARINA DE TRIGO, TOSTADAS, CAJETA Y COMIDA PROCESADA.',
    'BOLSA':'OFRECE PLATAFORMAS DE NEGOCIACIÓN Y LIQUIDACIÓN PARA ACCIONES Y DERIVADOS FINANCIEROS, OPERACIÓN DE RENTA FIJA Y DERIVADOS OTC. ADEMÁS DE SERVICIOS DE CUSTODIA Y LISTADO DE VALORES.',
    'CABLE':'CONCESIONARIA PARA INSTALAR, OPERAR Y EXPLOTAR UNA RED PUBLICA DE TELECOMUNICACIONES QUE PRESTA SERVICIOS DE TELEVISION POR CABLE Y AUDIO RESTRINGIDOS.',
    'CADU':'CONTROLADORA DE ACCIONES CUYA ACTIVIDAD PRINCIPAL ES DESARROLLO DE VIVIENDA DE INTERÉS SOCIAL.',
    'CEMEX':'FABRICACION Y VENTA DE TODA CLASE DE CEMENTOS.',
    'CERAMIC':'FABRICACION Y COMERCIALIZACION DE LOSETA CERAMICA PARA PISOS Y RECUBRIMIENTOS.',
    'CHDRAUI':'CONTROLADORA DE EMPRESAS DEDICADAS A LA COMERCIALIZACIÓN DE DIVERSOS ARTICULOS A TRAVES DE TIENDAS DE AUTOSERVICIO Y DEPARTAMENTALES, ASI COMO PANIFICADORAS INTEGRADAS.',
    'CIDMEGA':'CONTROLADORA DE ACCIONES DE EMPRESAS DEDICADAS A LA OPERACION DE HOTELES; VENTA DE TIEMPO COMPARTIDO; VENTA DE BIENES RAICES; OPERACION DE MARINAS; CLUBS DE GOLF Y CLUB NAUTICO.',
    'CIE':'CONTROLADORA DEDICADA A LA INDUSTRIA DEL ENTRETENIMIENTO, PROMOCIÓN Y ORGANIZACIÓN Y VENTA DE BOLETOS PARA EVENTOS, DE VEHÍCULOS PUBLICITARIOS Y MKT, OPERACIÓN DE RECINTOS.',
    'CMOCTEZ':'ES UNA EMPRESA CONTROLADORA ESPECIALIALIZADA A TRAVES DE SUS SUBSIDIARIAS EN LA PRODUCCIÓN, TRANSPORTE Y BOMBEO DE CONCRETO PREMEZCLADO.',
    'CMR':'CONTROLADORA PURA DE ACCIONES DE EMPRESAS DEDICADAS A LA OPERACIÓN DE CAFETERIAS, RESTAURANTES Y BARES EN LA REPÚBLICA MEXICANA.',
    'COLLADO':'COMPRA - VENTA, TRANSFORMACION, MAQUILA Y DISTRIBUCION DE PRODUCTOS DE ACERO, EMPLEADOS PRINCIPALMENTE EN LA INDUSTRIA DE LA CONSTRUCCION.',
    'CONVER':'COMPRA-VENTA, MAQUILA Y FABRICACION DE TODA CLASE DE ARTICULOS PLASTICOS Y METALICOS.',
    'CREAL':'OPERACIONES DE CREDITO, ARRENDAMIENTO FINANCIERO Y FACTORAJE FINANCIERO, BAJO EL CARÁCTER DE ACREDITANTE, ARRENDADOR Y FACTORANTE.',
    'CUERVO':'PRODUCTORA DE TEQUILA Y PARTICIPANTE EN LA INDUSTRIA DE BEBIDAS ALCOHÓLICAS A NIVEL MUNDIAL.',
    'CULTIBA':'TENEDORA DE ACCIONES DE EMPRESAS DEDICADAS A LA PRODUCCION, DISTRIBUCION, COMPRA-VENTA Y COMERCIALIZACION DE REFRESCOS ENVASADOS, Y TAMBIEN EN AZÚCAR DE CAÑA Y MIELES INCRISTALIZABLES.',
    'CYDSASA':'CONTROLADORA DE EMPRESAS INDUSTRIALES COMERCIALES Y DE SERVICIOS QUE OPERAN EN AREAS DIVERSIFICADAS.',
    'DINE':'DESARROLLOS INMOBILIARIOS.',
    'EDOARDO':'TENEDORA DE ACCIONES DE UN GRUPO DE COMPAÑIAS QUE SE DEDICAN A LA CONFECCION, FABRICACION Y COMERCIALIZACION DE TELAS Y PRENDAS DE VESTIR.',
    'ELEKTRA':'COMPAÑÍA DE SERVICIOS FINANCIEROS Y DE COMERCIO ESPECIALIZADO ENFOCADA A LA BASE DE LA PIRÁMIDE SOCIOECONÓMICA.',
    'ELEMENT':'FABRICANTE DE PRODUCTOS DE COBRE, FIBROCEMENTO, CONCRETO, POLIETILENO, POLIPROPILENO Y ESTIRENO.',
    'FEMSA':'LA CADENA DE TIENDAS DE CONVENIENCIA MAS EXTENSA Y DE MAYOR CRECIMIENTO EN AMERICA',
    'FINAMEX':'CONTROLADORA DE EMPRESAS DEDICADAS A PRESTAR SERVICIOS FINANCIEROS DIVERSOS.',
    'FINDEP':'OTORGAMIENTO DE CREDITOS PARA LA ADQUISICION DE BIENES Y SERVICIOS DE CONSUMO.',
    'FRAGUA':'CONTROLADORA DE EMPRESAS DEDICADAS PRINCIPALMENTE A LA COMPRA-VENTA DE MEDICINAS, PERFUMERIA, FOTOGRAFIA, ETC.',
    'GAP':'PRESTACIÓN DE SERVICIOS AEROPORTUARIOS A TRAVÉS DE LOS DOCE AEREOPUERTOS QUE OPERA LA COMPAÑÍA EN LA REGIÓN DEL PACÍFICO.',
    'GBM':'INTERMEDIARIO BURSATIL.',
    'GCARSO':'CONTROLADORA DE EMPRESAS DEDICADAS A DIVERSAS AREAS DE LA ACTIVIDAD ECONOMICA.',
    'GCC':'PRODUCCION, DISTRIBUCION Y COMERCIALIZACION DE CEMENTO PORTLAND, CONCRETO Y MATERIALES PARA LA CONSTRUCCION.',
    'GENSEG':'SEGUROS.',
    'GENTERA':'PROMOVER, ORGANIZAR Y ADMINISTRAR TODA CLASE DE SOCIEDADES MERCANTILES O CIVILES.',
    'GEO':'DISEÑO, DESARROLLO, CONSTRUCCION Y VENTA DE UNIDADES HABITACIONALES.',
    'GFAMSA':'COMERCIALIZAR EN LA REPUBLICA MEXICANA PRODUCTOS NACIONALES E IMPORTADOS DE LINEA BLANCA, APARATOS ELECTRODOMESTICOS, MUEBLES Y ROPA.',
    'GFINBUR':'CONTROLADORA PURA DE ACCIONES DE EMPRESAS QUE PRESTAN SERVICIOS FINANCIEROS.',
    'GFINTER':'CONTROLADORA DE EMPRESAS DEDICADAS A PRESTAR SERVICIOS FINANCIEROS.',
    'GFMULTI':'SOCIEDAD CONTROLADORA DE EMPRESAS QUE OPERAN DENTRO DEL AREA DE SERVICIOS FINANCIEROS.',
    'GFNORTE':'CONTROLADORA DE EMPRESAS QUE PRESTAN SERVICIOS FINANCIEROS.',
    'GFREGIO':'CONTROLADORA DE ENTIDADES FINANCIERAS, PRODUCTOS Y SERVICIOS FINANCIEROS A EMPRESAS, PARTICULARMENTE PEQUEÑAS Y MEDIANAS (PYMES) ASÍ COMO CRÉDITOS HIPOTECARIOS, DE CONSUMO Y PRODUCTOS DE CAPTACIÓN PARA PERSONAS FÍSICAS.',
    'GICSA':'DESAROLLADORA INMOBILIARIA.',
    'GIGANTE':'TENEDORA PURA DE ACCIONES DE EMPRESAS DEDICADAS A LA COMERCIALIZACION DE MERCANCIAS BAJO EL SISTEMA DE AUTOSERVICIO, A LA OPERACION DE RESTAURANTES Y AL DESARROLLO DE CENTROS COMERCIALES.',
    'GISSA':'CONTROLADORA DE EMPRESAS INDUSTRIALES QUE OPERAN EN AREAS DIVERSIFICADAS: AUTOPARTES, CONTRUCCION, HOGAR.',
    'GMD':'SOCIEDAD CONTROLADORA DE EMPRESAS DEDICADAS A LA PROMOCIÓN, INVERSIÓN, DESARROLLO, CONSTRUCCIÓN, Y OPERACIÓN DE PROYECTOS DE INFRAESTRUCTURA E INMOBILIARIOS.',
    'GMEXICO':'PROCESAMIENTO DE COBRE, ZINC, PLATA, ORO, PLOMO Y MOLIBDENO.',
    'GNP':'SEGUROS.',
    'GOMO':'CONTROLADORA DE ACCIONES DE EMPRESAS DEDICADAS A LA COMERCIALIZACION, DISTRIBUCION, COMPRA VENTA, DE TODA CLASE DE APARATOS ELECTRICOS, ELECTRODOMESTICOS Y OTROS PRODUCTOS SIMILARES.',
    'GPH':'CONTROLADORA DE EMPRESAS DEDICADAS PRINCIPALMENTE A LA COMERCIALIZACION DE ARTICULOS Y ACCESORIOS PARA USO PERSONAL Y PARA EL HOGAR.',
    'GPROFUT':'PROMOVER, OPERAR Y DESARROLLAR TODO TIPO DE EMPRESAS Y PARTICIPAR EN SU CAPITAL, INCLUYENDO COMPAÑÍAS DE SEGUROS, DE PENSIONES, ADMINISTRADORAS DE FONDOS DE AHORRO PARA EL RETIRO.',
    'GSANBOR':'CONTROLADORA DE EMPRESAS DEDICADAS A LA OPERACION DE TIENDAS DEPARTAMENTALES Y RESTAURANTES, FABRICACION CHOCOLATES Y ARTICULOS DE TOCADOR, ARRENDAMIENTO Y ADMINISTRACION DE CENTROS COMERCIALES.',
    'HCITY':'DISEÑO, ADMINISTRACIÓN, OPERACIÓN Y FRANQUICIA DE HOTELES DE SERVICIO LIMITADO',
    'HERDEZ':'PRODUCCIÓN, DISTRIBUCIÓN Y COMERCIALIZACIÓN DE PRODUCTOS ALIMENTICIOS EN CONSERVA, ENLATADOS Y ENVASADOS.',
    'HILASAL':'FABRICACION Y VENTA DE TOALLAS Y BATAS DE DIFERENTES ESTAMPADOS Y TAMAÑOS, TANTO PARA BAÑO COMO DE PLAYA.',
    'HOMEX':'CONSTRUCCION DE VIVIENDAS.',
    'HOTEL':'HOTELES Y CENTROS DE VACACIONES.',
    'IASASA':'FABRICACION Y VENTA DE AUTOPARTES ESTAMPADAS DE ACERO Y FABRICACION DE RUEDAS Y RIMS PARA VEHICULOS DE AUTOPARTES TANTO PARA EQUIPO ORIGINAL COMO DE REPUESTO.',
    'ICA':'SOCIEDAD CONTROLADORA DE EMPRESAS DEDICADAS A LA CONSTRUCCION PESADA, INDUSTRIAL O URBANA ASI COMO A DIVERSAS OBRAS DE INGENIERIA Y SERVICIOS.',
    'ICH':'EMPRESA MEXICANA DEDICADA A LA PRODUCCIÓN DE ACERO LA CUAL CUENTA CON PLANTAS EN MÉXICO, EUA Y CANADÁ.',
    'IDEAL':'ADQUIRIR TODO TIPO DE ACCIONES, PARTES SOCIALES Y PARTICIPACIONES EN TODO TIPO DE ASOCIACIONES.',
    'IENOVA':'SECTOR ENERGETICO. SERVICIO DE GAS Y ELECTRICIDAD.',
    'INGEAL':'ELABORACION DE PRODUCTOS ALIMENTICOS.',
    'INVEX':'CONTROLADORA PURA TENEDORA DE ACCIONES DE ENTIDADES FINANCIERAS.',
    'JAVER':'PROMOCION, FOMENTO, DESARROLLO, ADQUISICION, ENAJENACION, USO, EXPLOTACION, URBANIZACION, NOTIFICACION, EDIFICACION, Y ACONDICIONAMIENTO DE TODA CLASE DE INMUEBLES.',
    'KIMBER':'MANUFACTURA Y MERCADEO DE PRODUCTOS PARA EL CONSUMIDOR Y PARA EL CUIDADO DE LA SALUD Y PARA INSTITUCIONES.',
    'KOF':'TENEDORA DE ACCIONES DE LAS COMPAÑIAS OPERADORAS DE LA DIVISION DE BEBIDAS NO ALCOHÓLICAS DE GRUPO FEMSA.',
    'KUO':'SOCIEDAD DE FOMENTO INDUSTRIAL.',
    'LAB':'DESARROLLO, COMERCIALIZACIÓN Y DISTRIBUCIÓN DE MEDICAMENTOS QUE NO REQUIEREN RECETA PARA SU VENTA, ASÍ COMO PRODUCTOS DE BELLEZA Y CUIDADO PERSONAL.',
    'LACOMER':'SUPERMERCADOS E HIPERMERCADOS. COMERCIO DE PRODUCTOS PERECEDEROS, ABARROTES, MERCANCIAS GENERALES.',
    'LALA':'RECOLECCION, ENFRIAMIENTO, PASTEURIZACION, ENVASADO, TRANSPORTACION Y COMERCIALIZACION DE LECHE Y ALGUNOS DERIVADOS.',
    'LAMOSA':'MANUFACTURA Y VENTA DE PRODUCTOS PARA LA CONSTRUCCIÓN COMO REVESTIMIENTOS CERÁMICOS Y ADHESIVOS CERÁMICOS.',
    'LASEG':'SEGUROS.',
    'LIVEPOL':'CONTROLADORA DE ALMACENES DE ROPA Y ARTICULOS PARA EL HOGAR.',
    'MASECA':'PRODUCTOR MAS GRANDE DE HARINA DE MAIZ EN MEXICO.',
    'MAXCOM':'SERVICIOS DE TELECOMUNICACIONES.',
    'MEDICA':'DESARROLLO DE COMPLEJOS INTEGRALES DE SALUD QUE CONTEMPLAN, CONSULTORIOS MEDICOS, CLINICAS DE DIAGNOSTICO Y TRATAMIENTO, HOSPITALIZACION, INVESTIGACION Y DOCENCIA.',
    'MEGA':'TENEDORA DE ACCIONES DE EMPRESAS DEDICADAS A ACITIVIDADES REALACIONADAS CON LOS SERVICIOS DE TELEVISION POR CABLE.',
    'MEXCHEM':'EMPRESA DEDICADA A LA ELABORACION DE PRODUCTOS QUIMICOS, PETROQUIMICOS, ACIDO FLUORHIDRICO Y EXTRACCION DE FLUORITA.',
    'MFRISCO':'METALES Y MINERIA.',
    'MINSA':'FABRICACION DE HARINA DE MAIZ NIXTAMALIZADO, MAIZ NIXTAMALIZADO DESHIDRATADO Y TORTILLA EMPACADA.',
    'MONEX':'COMPRAVENTA DE DIVISAS Y PAGOS INTERNACIONALES, CRÉDITO Y LÍNEAS DE CRÉDITO COMERCIAL, PRODUCTOS MANEJO DE RIESGO, SERVICIO DE INTERMEDIACIÓN BURSÁTIL, SERVICIOS FIDUCIARIOS, SOCIEDADES DE INVERSIÓN.',
    'NEMAK':'PROVEEDOR DE SOLUCIONES DE ALIGERAMIENTO PARA LA INDUSTRIA AUTOMOTRIZ, ESPECIALIZADO EN EL DESARROLLO Y MANUFACTURA DE COMPONENTES DE ALUMINIO PARA TREN MOTRIZ Y CARROCERÍA DE AUTOMÓVILES.',
    'OHLMEX':'ES UNO DE LOS PRINCIPALES OPERADORES EN EL SECTOR PRIVADO DE CONCESIONES EN INFRAESTRUCTURA DE TRANSPORTE EN MÉXICO.',
    'OMA':'SERVICIOS DE ADMINISTRACION DE AEROPUERTOS Y HELIPUERTOS.',
    'PAPPEL':'CONTROLADORA DE EMPRESAS QUE OPERAN EN LA INDUSTRIA PAPELERA Y PRODUCTOS DE PAPEL.',
    'PASA':'SERVICIOS MEDIOAMBIENTALES Y DE MANTENIMIENTO DE INSTALACIONES.',
    'PE&OLES':'CONTROLADORA DE EMPRESAS DEDICADAS A LA EXPLOTACION MINERA, FUNDICION, REFINACION, MANUFACTURA DE METALES NO FERROSOS Y FABRICACION DE PRODUCTOS QUIMICOS Y REFRACTARIOS.',
    'PINFRA':'CONTROLADORA DE EMPRESAS DEDICADAS AL DISEÑO, PLANEACION Y CONSTRUCCION DE TODO GENERO DE OBRAS PUBLICAS Y PRIVADAS.',
    'PLANI':'DESARROLLO Y ADQUISICIÓN DE CENTROS COMERCIALES.',
    'POCHTEC':'CONTROLADORA DE ACCIONES DE EMPRESAS DEDICADAS A LA FABRICACION Y COMERCIALIZACION DE PRODUCTOS QUIMICOS, FARMACEUTICOS Y PARA LA INDUSTRIA ALIMENTICIA EN GENERAL.',
    'POSADAS':'CONSTRUCCION, ADQUISICION, ARRENDAMIENTO Y OPERACION DE HOTELES.',
    'PROCORP':'COMPRA-VENTA DE VALORES DE EMPRESAS QUE REQUIEREN DE RECURSOS A LARGO PLAZO.',
    'PV':'SOCIEDAD CONTROLADORA DE REASEGURADORA PATRIA Y GENERAL DE SEGUROS.',
    'Q':'ORGANIZACIÓN, PROMOCION Y ADMINISTRACION DE TODA CLASE DE SOCIEDADES MERCANTILES Y CIVILES.',
    'QBINDUS':'ELABORACION Y VENTA DE DIVERSOS PRODUCTOS QUIMICOS, PRINCIPALMENTE DE RESINAS NATURALES Y SINTETICAS.',
    'QUMMA':'EMPRESA DEDICADA A LA COMUNICACION ESCRITA, LAS ARTES GRAFICAS, EL ENTRETENIMIENTO, ARTICULOS PROMOCIONALES Y LA INDUSTRIA DEL RECONOCIMIENTO.',
    'RASSINI':'CONTROLADORA DE EMPRESAS QUE OPERAN EN LA INDUSTRIA DE AUTOPARTES.',
    'RCENTRO':'PRODUCCION Y TRANSMISION DE PROGRAMAS MUSICALES Y DE ENTRETENIMIENTO, PROGRAMAS DE INFORMACION Y ANALISIS, DE NOTICIAS Y DE EVENTOS ESPECIALES.',
    'RLH':'ADQUISICIÓN Y DESARROLLO DE ACTIVOS HOTELEROS DE CIUDAD Y PLAYA UBICADOS EN LOS PRINCIPALES CENTROS URBANOS.',
    'SAB':'DISTRIBUCION DE PRODUCTOS FARMACEUTICOS, DE BELLEZA, CUIDADO PERSONAL Y DE CONSUMO Y MERCADERIAS GENERALES; OPERACIÓN DE UNA DE LAS CADENAS DE FARMACIAS MAS IMPORTANTES EN AMERICA LATINA.',
    'SANMEX':'CONTROLADORA DE EMPRESAS ESPECIALIZADAS EN EL SECTOR FINANCIERO.',
    'SARE':'PARTICIPAR EN EL CAPITAL SOCIAL DE SUS SUBSIDIARIAS, EMPRESAS DEDICADAS A LA PROMOCIÓN DE VIVIENDA PARA LOS SEGMENTOS DE INTERÉS SOCIAL, MEDIO Y RESIDENCIAL, Y LA PRESTACIÓN DE SERVICIOS INMOBILIARIOS.',
    'SAVIA':'INVESTIGACION, PRODUCCION Y COMERCIALIZACION DE SEMILLAS Y PRODUCTOS FRESCOS.',
    'SIMEC':'PRODUCCIÓN DE ACERO LA CUAL CUENTA CON PLANTAS EN MÉXICO, EUA Y CANADÁ.',
    'SITES':'ARRENDAMIENTO DE SITIOS DE TELECOMUNICACIONES.',
    'SORIANA':'POR MEDIO DE SUS SUBSIDIARIAS, LA COMERCIALIZACION DE ARTICULOS BASICOS EN LA ALIMENTACION, VESTIDO E INDISPENSABLES PARA EL HOGAR POR MEDIO DEL SISTEMA DE AUTOSERVICIO.',
    'SPORT':'OPERACION DE CLUBES DEPORTIVOS A TRAVES DE LOCALES ESTABLECIDOS EN LAS PRINCIPALES ZONAS COMERCIALES Y HABITACIONALES DE LA CIUDAD DE MEXICO Y EN ALGUNAS CIUDADES IMPORTANTES DEL INTERIOR DE LA REPUBLICA MEXICANA.',
    'TEAK':'PRODUCTOR DE TECA',
    'TEKCHEM':'FABRICACION Y VENTA DE PRODUCTOS QUIMICOS Y AGROQUIMICOS.',
    'TLEVISA':'COMPAÑÍA DE MEDIOS DE COMUNICACIÓN MÁS GRANDE EN EL MUNDO DE HABLA HISPANA.',
    'TMM':'TRANSPORTACIÓN MULTIMODAL Y SERVICIOS DE LOGISTICA.',
    'UNIFIN':'ARRENDAMIENTO PURO, FACTORAJE FINANCIERO Y CRÉDITO AUTOMOTRIZ.',
    'URBI':'CONSTRUCCION, PROMOCION Y VENTA DE VIVIENDA.',
    'VALUEGF':'CONTROLADORA DE EMPRESAS DEDICADAS A PRESTAR SERVICIOS FINANCIEROS ESPECIALIZADOS.',
    'VASCONI':'FABRICACION Y VENTA DE ARTICULOS DE ALUMINIO Y ACERO PARA EL HOGAR.',
    'VESTA':'DESARROLLO INMOBILIARIO INDUSTRIAL.',
    'VINTE':'DESARROLLO, PROMOCIÓN, DISEÑO, CONSTRUCCIÓN Y COMERCIALIZACIÓN DE VIVIENDA.',
    'VITRO':'CONTROLADORA DE EMPRESAS EN AREAS DIVERSIFICADAS,PRINCIPALMENTE LAS DE VIDRIO.',
    'VOLAR':'LINEAS AEREAS.',
    'WALMEX':'CONTROLADORA DE CADENAS DE TIENDAS DE DESCUENTO Y ROPA.'
    }



# %% name2ticker

name2ticker = {

'Arca Continental, S.A.B. de C.V.':'AC','ACCEL, S.A.B. de C.V.':'ACCELSA',
'Corporación Actinver, S.A.B. de C.V.':'ACTINVR','Grupo Aeroméxico, S.A.B. de C.V.':'AEROMEX',
'Agro Industrial Exportadora, S.A. de C.V.':'AGRIEXP','Grupo Rotoplas, S.A.B. de C.V.':'AGUA',
'Altos Hornos de México, S.A. de C.V.':'AHMSA','Alfa, S.A.B. de C.V.':'ALFA','Alpek, S.A.B. de C.V.':'ALPEK',
'Alsea, S.A.B. de C.V.':'ALSEA','América Móvil, S.A.B. de C.V.':'AMX','Consorcio Ara, S.A.B. de C.V.':'ARA',
'Consorcio Aristos, S.A.B. de C.V.':'ARISTOS','Grupo Aeroportuario del Sureste, S.A.B. de C.V.':'ASUR',
'Compañía Minera Autlán, S.A.B. de C.V.':'AUTLAN','Axtel, S.A.B. de C.V.':'AXTEL','TV Azteca, S.A.B. de C.V.':'AZTECA',
'Industrias Bachoco, S.A.B. de C.V.':'BACHOCO','Grupo Bafar, S.A.B. de C.V.':'BAFAR','Farmacias Benavides, S.A.B. de C.V.':'BEVIDES',
'Grupo Bimbo, S.A.B. de C.V.':'BIMBO','Bolsa Mexicana de Valores, S.A.B. de C.V.':'BOLSA','Empresas Cablevisión, S.A. de C.V.':'CABLE',
'Corpovael, S.A.B. de C.V.':'CADU','Cemex, S.A.B. de C.V.':'CEMEX','Internacional de Cerámica, S.A.B. de C.V.':'CERAMIC',
'Grupo Comercial Chedraui, S.A.B. de C.V.':'CHDRAUI','Grupe, S.A.B. de C.V.':'CIDMEGA',
'Corporación Interamericana de Entretenimiento, S.A.B. de C.V.':'CIE','Corporación Moctezuma, S.A.B. de C.V.':'CMOCTEZ',
'CMR, S.A.B. de C.V.':'CMR','G Collado, S.A.B. de C.V.':'COLLADO','Convertidora Industrial, S.A.B. de C.V.':'CONVER',
'Crédito Real, S.A.B. de C.V., Sofom, E.R.':'CREAL','BECLE, S.A.B. de C.V.':'CUERVO',
'Organización Cultiba, S.A.B. de C.V.':'CULTIBA','CYDSA, S.A.B. de C.V.':'CYDSASA',
'Dine, S.A.B. de C.V.':'DINE','Edoardos Martin, S.A.B. de C.V.':'EDOARDO','Grupo Elektra, S.A.B. de C.V.':'ELEKTRA',
'Elementia, S.A.B. de C.V.':'ELEMENT','Fomento Económico Mexicano, S.A.B. de C.V.':'FEMSA',
'Casa de Bolsa Finamex, S.A.B. de C.V.':'FINAMEX','Financiera Independencia, S.A.B. de C.V. Sofom, E.N.R.':'FINDEP',
'Corporativo Fragua, S.A.B. de C.V.':'FRAGUA','Grupo Aeroportuario del Pacífico, S.A.B. de C.V.':'GAP',
'Corporativo GBM, S.A.B. de C.V.':'GBM','Grupo Carso, S.A.B. de C.V.':'GCARSO','Grupo Cementos de Chihuahua, S.A.B. de C.V.':'GCC',
'General de Seguros, S.A.B. de C.V.':'GENSEG','Gentera, S.A.B. de C.V.':'GENTERA','Corporación Geo, S.A.B. de C.V.':'GEO',
'Grupo Famsa, S.A.B. de C.V.':'GFAMSA','Grupo Financiero Inbursa, S.A.B. de C.V.':'GFINBUR',
'Grupo Financiero Interacciones, S.A. de C.V.':'GFINTER','Grupo Financiero Multiva, S.A.B. de C.V.':'GFMULTI',
'Grupo Financiero Banorte, S.A.B. de C.V.':'GFNORTE','Banregio Grupo Financiero':'GFREGIO',
'Grupo Gicsa, S.A.B. de C.V.':'GICSA','Grupo Gigante, S.A.B. de C.V.':'GIGANTE','Grupo Industrial Saltillo, S.A.B. de C.V.':'GISSA',
'Grupo Mexicano de Desarrollo, S.A.B. de C.V.':'GMD','Grupo México, S.A.B. de C.V.':'GMEXICO',
'Grupo Nacional Provincial, S.A.B.':'GNP','Grupo Comercial Gomo, S.A. de C.V.':'GOMO','Grupo Palacio de Hierro, S.A.B. de C.V.':'GPH',
'Grupo Profuturo, S.A.B. de C.V.':'GPROFUT','Gruma, S.A.B. de C.V.':'GRUMA','Grupo Sanborns, S.A.B. de C.V.':'GSANBOR',
'Hoteles City Express, S.A.B. de C.V.':'HCITY','Grupo Herdez, S.A.B. de C.V.':'HERDEZ','Hilasal Mexicana, S.A.B. de C.V.':'HILASAL',
'Desarrolladora Homex, S.A.B. de C.V.':'HOMEX','Grupo Hotelero Santa Fe, S.A.B. de C.V.':'HOTEL','Industria Automotriz, S.A. de C.V.':'IASASA',
'Empresas ICA, S.A.B. de C.V.':'ICA','Industrias CH, S.A.B. de C.V.':'ICH','Impulsora del Desarrollo y el Empleo en América Latina, S.A.B. de C.V.':'IDEAL',
'Infraestructura Energética Nova, S.A.B. de C.V.':'IENOVA','Ingeal, S.A.B. de C.V.':'INGEAL','Invex Controladora, S.A.B. de C.V.':'INVEX',
'Servicios Corporativos Javer, S.A.B. de C.V.':'JAVER','Kimberly-Clark de México, S.A.B. de C.V.':'KIMBER',
'Coca-Cola Femsa, S.A.B. de C.V.':'KOF','Grupo Kuo, S.A.B. de C.V.':'KUO','Genomma Lab Internacional, S.A.B. de C.V.':'LAB',
'La Comer, S.A.B. de C.V.':'LACOMER','Grupo LALA, S.A.B. de C.V.':'LALA','Grupo Lamosa, S.A.B. de C.V.':'LAMOSA',
'La Latinoamericana Seguros, S.A.':'LASEG','El puerto de Liverpool, S.A.B. de C.V.':'LIVEPOL','Grupo Industrial Maseca, S.A.B. de C.V.':'MASECA',
'Maxcom Telecomunicaciones, S.A.B. de C.V.':'MAXCOM','Medica Sur, S.A.B. de C.V.':'MEDICA','Megacable Holdings, S.A.B. de C.V.':'MEGA',
'Mexichem, S.A.B. de C.V.':'MEXCHEM','Minera Frisco, S.A.B. de C.V.':'MFRISCO','Grupo Minsa, S.A.B. de C.V.':'MINSA','Monex, S.A.B. de C.V.':'MONEX',
'Nemak, S.A.B. de C.V.':'NEMAK','OHL México, S.A.B. de C.V.':'OHLMEX','Grupo Aeroportuario del Centro Norte, S.A.B. de C.V.':'OMA',
'Bio pappel, S.A.B. de C.V.':'PAPPEL','Promotora Ambiental, S.A.B. de C.V.':'PASA','Industrias Peñoles, S.A.B. de C.V.':'PE&OLES',
'Promotora y Operadora de Infraestructura, S.A.B. de C.V.':'PINFRA','Planigrupo Latam, S.A.B. de C.V.':'PLANI',
'Grupo Pochteca, S.A.B. de C.V.':'POCHTEC','Grupo Posadas, S.A.B. de C.V.':'POSADAS','Procorp,S.A.B. de C.V.':'PROCORP',
'Peña Verde, S.A.B.':'PV','Quálitas Controladora, S.A.B. de C.V.':'Q','Q.B.Industrias, S.A. de C.V.':'QBINDUS','Grupo Qumma, S.A. de C.V.':'QUMMA',
'Rassini, S.A.B. de C.V.':'RASSINI','Grupo Radio Centro, S.A.B. de C.V.':'RCENTRO','RLH Properties, S.A.B. de C.V.':'RLH',
'Grupo Casa Saba, S.A.B. de C.V.':'SAB','Grupo Financiero Santander México, S.A.B. de C.V.':'SANMEX','Sare Holding, S.A.B. de C.V.':'SARE',
'Savia, S.A. de C.V.':'SAVIA','Grupo Simec, S.A.B. de C.V.':'SIMEC','Telesities, S.A.B. de C.V.':'SITIES','Organización Soriana, S.A.B. de C.V.':'SORIANA',
'Grupo Sports World, S.A.B. de C.V.':'SPORT','Proteak Uno, S.A.B. de C.V.':'TEAK','Tekchem, S.A.B. de C.V.':'TEKCHEM','Grupo Televisa, S.A.B.':'TLEVISA',
'Grupo Tmm,S.A.':'TMM','Unifin Financiera, S.A.B. de C.V.,Sofom, E.N.R.':'UNIFIN','Urbi Desarrollos Urbanos, S.A.B. de C.V.':'URBI',
'Value Grupo Financiero, S.A.B. de C.V.':'VALUEGF','Grupo Vasconia, S.A.B.':'VASCONI',
'Corporación Inmobiliaria Vesta, S.A.B. de C.V.':'VESTA','Vinte Vivieandas Integrales, S.A.B. de C.V.':'VINTE','Vitro, S.A.B. de C.V.':'VITRO',
'Controladora Vuela Compañía de Aviación, S.A.B. de C.V.':'VOLAR','Wal-Mart de México, S.A.B. de C.V.':'WALMEX'
}

# %% ticker2yahoo

ticker2yahoo = {

'AC':'AC.MX','ACCELSA':'ACCELSAB.MX','ACTINVR':'ACTINVRB.MX','AEROMEX':'AEROMEX.MX','AGRIEXP':None,'AGUA':'AGUA.MX',
'AHMSA':None,'ALFA':'ALFAA.MX','ALPEK':'ALPEKA.MX','ALSEA':'ALSEA.MX','AMX':'AMXL.MX','ARA':'ARA.MX','ARISTOS':None,
'ASUR':'ASURB.MX','AUTLAN':'AUTLANB.MX','AXTEL':'AXTELCPO.MX','AZTECA':'AZTECACPO.MX','BACHOCO':'BACHOCOB.MX','BAFAR':'BAFARB.MX',
'BEVIDES':'BEVIDESB.MX','BIMBO':'BIMBOA.MX','BOLSA':'BOLSAA.MX','CABLE':None,'CADU':'CADUA.MX','CEMEX':'CEMEXCPO.MX','CERAMIC':'CERAMICD.MX',
'CHDRAUI':'CHDRAUIB.MX','CIDMEGA':'CIDMEGA.MX','CIE':None,'CMOCTEZ':'CMOCTEZ.MX','CMR':None,'COLLADO':'COLLADO.MX','CONVER':None,
'CREAL':'CREAL.MX','CUERVO':'CUERVO.MX','CULTIBA':'CULTIBAB.MX','CYDSASA':'CYDSASAA.MX','DINE':'DINEB.MX','EDOARDO':'EDOARDOB.MX',
'ELEKTRA':'ELEKTRA.MX','ELEMENT':'ELEMENT.MX','FEMSA':'FEMSAUB.MX','FINAMEX':'FINAMEXO.MX','FINDEP':'FINDEP.MX',
'FRAGUA':'FRAGUAB.MX','GAP':'GAPB.MX','GBM':'GBMO.MX','GCARSO':'GCARSOA1.MX','GCC':'GCC.MX','GENSEG':None,'GENTERA':'GENTERA.MX',
'GEO':None,'GFAMSA':'GFAMSAA.MX','GFINBUR':'GFINBURO.MX','GFINTER':'GFINTERO.MX','GFMULTI':'GFMULTIO.MX','GFNORTE':'GFNORTEO.MX',
'GFREGIO':'GFREGIOO.MX','GICSA':'GICSAB.MX','GIGANTE':'GIGANTE.MX','GISSA':'GISSAA.MX','GMD':'GMD.MX','GMEXICO':'GMEXICOB.MX',
'GNP':'GNP.MX','GOMO':None,'GPH':'GPH1.MX','GPROFUT':'GPROFUT.MX','GRUMA':'GRUMAB.MX','GSANBOR':'GSANBORB-1.MX',
'HCITY':'HCITY.MX','HERDEZ':'HERDEZ.MX','HILASAL':'HILASALA.MX','HOMEX':'HOMEX.MX','HOTEL':None,'IASASA':None,
'ICA':'ICA.MX','ICH':None,'IDEAL':'IDEALB-1.MX','IENOVA':'IENOVA.MX','INGEAL':None,'INVEX':'INVEXA.MX',
'JAVER':'JAVER.MX','KIMBER':'KIMBERA.MX','KOF':'KOFL.MX','KUO':'KUOB.MX','LAB':'LABB.MX','LACOMER':'LACOMERUBC.MX',
'LALA':'LALAB.MX','LAMOSA':'LAMOSA.MX','LASEG':None,'LIVEPOL':'LIVEPOLC-1.MX','MASECA':'MASECAB.MX',
'MAXCOM':'MAXCOMA.MX','MEDICA':None,'MEGA':'MEGACPO.MX','MEXCHEM':'MEXCHEM.MX','MFRISCO':'MFRISCOA-1.MX','MINSA':'MINSAB.MX','MONEX':'MONEXB.MX',
'NEMAK':'NEMAKA.MX','OHLMEX':'OHLMEX.MX','OMA':'OMAB.MX','PAPPEL':'PAPPEL.MX','PASA':'PASAB.MX','PE&OLES':'PE&OLES.MX',
'PINFRA':'PINFRA.MX','PLANI':'PLANI.MX','POCHTEC':'POCHTECB.MX','POSADAS':'POSADASA.MX','PROCORP':'PROCORPA.MX','PV':'PV.MX',
'Q':'Q.MX','QBINDUS':None,'QUMMA':None,'RASSINI':'RASSINIA.MX','RCENTRO':'RCENTROA.MX','RLH':'RLHA.MX',
'SAB':None,'SANMEX':'SANMEXB.MX','SARE':'SAREB.MX','SAVIA':None,'SIMEC':'SIMECB.MX','SITIES':None,
'SORIANA':'SORIANAB.MX','SPORT':'SPORTS.MX','TEAK':'TEAKCPO.MX','TEKCHEM':None,'TLEVISA':'TLEVISACPO.MX',
'TMM':'TMMA.MX','UNIFIN':'UNIFINA.MX','URBI':'URBI.MX','VALUEGF':'VALUEGFO.MX','VASCONI':'VASCONI.MX',
'VESTA':'VESTA.MX','VINTE':'VINTE.MX','VITRO':'VITROA.MX','VOLAR':'VOLARA.MX','WALMEX':'WALMEX.MX'
}

# %% 

def main():
    
    np.save('name2desc.npy',name2desc)
    np.save('name2ticker.npy',name2ticker)
    np.save('ticker2yahoo.npy',ticker2yahoo)
    return 1 


# %% 

if __name__ == '__main__':    
    status = main()
    

